[package]
name = "rustafari"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sys-info = "0.9.0"
dmidecode = "0.7.7"
mac_address = "1.1.4"
local-ip-address = "0.5.6"